---- ===========================================================
---- População de recompensas básicas por dificuldade de expedição
---- ===========================================================
--
---- Floresta Misteriosa - Fácil
--UPDATE expedicao_dificuldade
--SET item_recompensa_id = 89, quantidade_item_recompensa = 1
--WHERE expedicao_id = 1 AND dificuldade = 'FACIL';
--
---- Floresta Misteriosa - Média
--UPDATE expedicao_dificuldade
--SET item_recompensa_id = 90, quantidade_item_recompensa = 1
--WHERE expedicao_id = 1 AND dificuldade = 'MEDIA';
--
---- Floresta Misteriosa - Difícil
--UPDATE expedicao_dificuldade
--SET item_recompensa_id = 91, quantidade_item_recompensa = 1
--WHERE expedicao_id = 1 AND dificuldade = 'DIFICIL';
--
---- Floresta Misteriosa - Extrema
--UPDATE expedicao_dificuldade
--SET item_recompensa_id = 92, quantidade_item_recompensa = 1
--WHERE expedicao_id = 1 AND dificuldade = 'EXTREMA';
