ALTER TABLE digimon
    ADD COLUMN iv_hp INT DEFAULT 1 CHECK (iv_hp BETWEEN 1 AND 100),
    ADD COLUMN iv_atk INT DEFAULT 1 CHECK (iv_atk BETWEEN 1 AND 100),
    ADD COLUMN iv_def INT DEFAULT 1 CHECK (iv_def BETWEEN 1 AND 100),
    ADD COLUMN iv_int INT DEFAULT 1 CHECK (iv_int BETWEEN 1 AND 100),
    ADD COLUMN iv_spd INT DEFAULT 1 CHECK (iv_spd BETWEEN 1 AND 100);