ALTER TABLE digimon
    ADD COLUMN ev_hp INT DEFAULT 0 CHECK (ev_hp BETWEEN 0 AND 252),
    ADD COLUMN ev_atk INT DEFAULT 0 CHECK (ev_atk BETWEEN 0 AND 252),
    ADD COLUMN ev_def INT DEFAULT 0 CHECK (ev_def BETWEEN 0 AND 252),
    ADD COLUMN ev_int INT DEFAULT 0 CHECK (ev_int BETWEEN 0 AND 252),
    ADD COLUMN ev_spd INT DEFAULT 0 CHECK (ev_spd BETWEEN 0 AND 252),
    ADD COLUMN ev_total INT DEFAULT 0;