ALTER TABLE digimon
    ADD COLUMN int_ INT DEFAULT 0,

    ADD COLUMN crit_rate DECIMAL(5,2) DEFAULT 0.00,
    ADD COLUMN crit_damage DECIMAL(5,2) DEFAULT 0.00,
    ADD COLUMN accuracy DECIMAL(5,2) DEFAULT 0.00,
    ADD COLUMN evade DECIMAL(5,2) DEFAULT 0.00,
    ADD COLUMN bond DECIMAL(5,2) DEFAULT 0.00,

    ADD COLUMN personality VARCHAR(20);
