ALTER TABLE digimon
    ALTER COLUMN crit_rate TYPE DOUBLE PRECISION USING crit_rate::DOUBLE PRECISION,
    ALTER COLUMN crit_damage TYPE DOUBLE PRECISION USING crit_damage::DOUBLE PRECISION,
    ALTER COLUMN accuracy TYPE DOUBLE PRECISION USING accuracy::DOUBLE PRECISION,
    ALTER COLUMN evade TYPE DOUBLE PRECISION USING evade::DOUBLE PRECISION,
    ALTER COLUMN bond TYPE DOUBLE PRECISION USING bond::DOUBLE PRECISION;
